[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "sltforsgd"
version = "0.1.0"
description = "SGD analysis tools"

[tool.setuptools]
packages = ["lib"]